//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPL_HOME_TASK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentInformation()
        {
            this.FileInformations = new HashSet<FileInformation>();
            this.MetaDataInformations = new HashSet<MetaDataInformation>();
        }
    
        public long DocumentyIdentity { get; set; }
        public int CategoryId { get; set; }
        public string DocumentReferenceName { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string DocumentName { get; set; }
        public string DocumentNameBangla { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    
        public virtual DocumentCategoryInfo DocumentCategoryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInformation> FileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaDataInformation> MetaDataInformations { get; set; }
    }
}
