//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPL_HOME_TASK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaDataInformation
    {
        public long MetaIdentity { get; set; }
        public long DocumentyIdentity { get; set; }
        public string MetaName { get; set; }
        public string MetaNameBangla { get; set; }
        public string Description { get; set; }
    
        public virtual DocumentInformation DocumentInformation { get; set; }
    }
}
